import {
  DayOfWeek,
  RestaurantOperation,
} from '../models/restaurant-operation.model';

export const restaurantOperations: RestaurantOperation[] = [
  {
    id: 1,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.SUN,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 2,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.MON,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 3,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.TUES,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 4,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.WED,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 5,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.TURS,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 6,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.FRI,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
  {
    id: 7,
    restaurantId: 1,
    dayOfWeek: DayOfWeek.SAT,
    open: '0900',
    close: '2100',
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
  },
];
